name: Upload assets

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      RELEASE_VERSION: 0.0.4
      FILE_NAME: do_release.sh
      GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
    steps:
        - uses: actions/checkout@v2
    
        - name: upload assets
          run: echo "$RELEASE_VERSION" "$TEST_VARIABLE" "$ASSETS_TO_UPLOAD"
          env:
            ASSETS_TO_UPLOAD: ./adm-scripts/"$FILE_NAME"
            TEST_VARIABLE: hello world