name: Release Maven

on: 
  workflow_dispatch:
    inputs:
      release_version: # New version
        description: "Version of the new release"
        required: true


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2

        - name: Set up Apache Maven Central
          uses: actions/setup-java@v2
          with: # running setup-java to writes the settings.xml
            distribution: 'adopt'
            java-version: '11'
            server-id: ossrh # Value of the distributionManagement/repository/id field of the pom.xml
            server-username: OSSRH_USERNAME # env variable for username in deploy
            server-password: OSSRH_PASSWORD # env variable for token in deploy
            gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }} # Value of the GPG private key to import
            gpg-passphrase: MAVEN_GPG_PASSPHRASE # env variable for GPG private key passphrase

        - name: Publish package and commit in Github
          run: sh ./adm-scripts/do_release.sh ${{ github.event.inputs.release_version }}
          env:
            OSSRH_USERNAME: rsotosan
            OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
            MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}

        - name: Create Release
          id: create_release
          uses: actions/create-release@v1
          env:
            GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
          with:
            tag_name: ${{ github.event.inputs.release_version }}
            release_name: Release ${{ github.event.inputs.release_version }}
            draft: false
            prerelease: false

        - name: Upload Release Asset Parent POM
          id: upload-release-asset 
          uses: actions/upload-release-asset@v1
          env:
            GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
          with:
            upload_url: ${{ steps.create_release.outputs.upload_url }}
            asset_path: ./io.github.rsotosan.lib.parent/target/io.github.rsotosan.lib.parent-${{ github.event.inputs.release_version }}.pom
            asset_name: io.github.rsotosan.lib.parent-${{ github.event.inputs.release_version }}.pom
            asset_content_type: text/xml

        - name: Upload Release Asset Lib Math
          id: upload-release-asset 
          uses: actions/upload-release-asset@v1
          env:
            GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
          with:
            upload_url: ${{ steps.create_release.outputs.upload_url }}
            asset_path: io.github.rsotosan.lib.math/target/io.github.rsotosan.lib.math-${{ github.event.inputs.release_version }}.jar
            asset_name: io.github.rsotosan.lib.math-${{ github.event.inputs.release_version }}.jar
            asset_content_type: application/java-archive
        
        - name: Upload Release Asset Lib Text
          id: upload-release-asset 
          uses: actions/upload-release-asset@v1
          env:
            GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
          with:
            upload_url: ${{ steps.create_release.outputs.upload_url }}
            asset_path: io.github.rsotosan.lib.text/target/io.github.rsotosan.lib.text-${{ github.event.inputs.release_version }}.jar
            asset_name: io.github.rsotosan.lib.text-${{ github.event.inputs.release_version }}.jar
            asset_content_type: application/java-archive