name: Release Maven

on: 
  workflow_dispatch:
    inputs:
      release_version: # New version
        description: "Version of the new release"
        required: true


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2

        - name: Set up Apache Maven Central
          uses: actions/setup-java@v2
          with: # running setup-java to writes the settings.xml
            distribution: 'adopt'
            java-version: '11'
            server-id: ossrh # Value of the distributionManagement/repository/id field of the pom.xml
            server-username: OSSRH_USERNAME # env variable for username in deploy
            server-password: OSSRH_PASSWORD # env variable for token in deploy
            gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }} # Value of the GPG private key to import
            gpg-passphrase: MAVEN_GPG_PASSPHRASE # env variable for GPG private key passphrase
          env:
            OSSRH_USERNAME: rsotosan
            OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
            MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
            RELEASE_VERSION: ${{ github.event.inputs.release_version }}
            ASSETS_TO_UPLOAD: ./io.github.rsotosan.lib.parent/target/io.github.rsotosan.lib.parent-"$RELEASE_VERSION".pom
                              io.github.rsotosan.lib.math/target/io.github.rsotosan.lib.math-"$RELEASE_VERSION".jar
                              io.github.rsotosan.lib.text/target/io.github.rsotosan.lib.text-"$RELEASE_VERSION".jar
            GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}

        - name: Publish package and commit in Github
          run: sh ./adm-scripts/do_release.sh "$RELEASE_VERSION"

        - name: Create Release
          id: create_release
          uses: actions/create-release@v1
          with:
            tag_name: "$RELEASE_VERSION"
            release_name: Release "$RELEASE_VERSION"
            draft: false
            prerelease: false

        - name: Upload Assets          
          run: gh release upload $ASSETS_TO_UPLOAD